language: node_js
sudo: required
node_js:
  - "0.10"
install:
  - npm install -g eslint
  - npm install -g spacejam
script:
  - export PATH="$HOME/.meteor:$PATH"
  - cp settings.json.template settings.json
  - eslint .
  - spacejam test-packages

before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"

branches:
  only:
    - master
