language: node_js
sudo: false
node_js:
  - "0.12"
before_install:
  - curl -L http://git.io/ejPSng | /bin/sh
install:
  - npm install -g eslint
script:
  - export PATH="$HOME/.meteor:$PATH"
  - cp settings.json.template settings.json
  - eslint .

branches:
  only:
    - master
